# Form implementation generated from reading ui file 'giaodienchinh.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 542)
        MainWindow.setMinimumSize(QtCore.QSize(723, 542))
        MainWindow.setMaximumSize(QtCore.QSize(723, 542))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 723, 542))
        self.tabWidget.setMinimumSize(QtCore.QSize(723, 542))
        self.tabWidget.setMaximumSize(QtCore.QSize(723, 542))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    width: 150px;  /* Điều chỉnh độ rộng tab */\n"
"    height: 30px;  /* Điều chỉnh chiều cao tab */\n"
"}\n"
"QTabBar::tab:selected {\n"
"    font-weight: bold;  /* Làm đậm tab đang chọn */\n"
"}\n"
"QTabBar::tab {\n"
"    text-align: center;  /* Căn giữa chữ trong tab */\n"
"}\n"
"QTabBar {\n"
"    qproperty-alignment: center;\n"
"}")
        self.tabWidget.setIconSize(QtCore.QSize(20, 15))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 10, 261, 361))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    border: 2px solid black;       /* Viền ngoài bảng */\n"
"    gridline-color: black;         /* Màu đường kẻ ô */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0;     /* Màu nền header */\n"
"    border: 1px solid #aaa;        /* Viền header */\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(260)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(360, 10, 321, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    border: 1px solid black;  /* Viền 1px màu đen */\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.plnHienThongBao = QtWidgets.QPlainTextEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plnHienThongBao.setFont(font)
        self.plnHienThongBao.setStyleSheet("QPlainTextEdit {\n"
"    border: 1px solid black;  /* Viền 2px màu đen */\n"
"    border-radius: 3px;       /* Bo tròn góc 5px (nếu muốn) */\n"
"}")
        self.plnHienThongBao.setObjectName("plnHienThongBao")
        self.verticalLayout.addWidget(self.plnHienThongBao)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 400, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 1px solid black;         /* Viền đen 2px */\n"
"    border-radius: 10px;             /* Bo góc 10px */\n"
"    padding: 5px 15px;               /* Thêm padding cho nút */\n"
"    background-color: #f0f0f0;       /* Màu nền mặc định */\n"
"    color: black;                    /* Màu chữ */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0;       /* Màu nền khi di chuột vào */\n"
"    border: 2px solid darkgray;      /* Viền đổi thành màu xám đậm */\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 400, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 1px solid black;         /* Viền đen 2px */\n"
"    border-radius: 10px;             /* Bo góc 10px */\n"
"    padding: 5px 15px;               /* Thêm padding cho nút */\n"
"    background-color: #f0f0f0;       /* Màu nền mặc định */\n"
"    color: black;                    /* Màu chữ */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0;       /* Màu nền khi di chuột vào */\n"
"    border: 2px solid darkgray;      /* Viền đổi thành màu xám đậm */\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.QtblXuatThongTin_5 = QtWidgets.QTableWidget(parent=self.widget)
        self.QtblXuatThongTin_5.setGeometry(QtCore.QRect(360, 160, 321, 311))
        self.QtblXuatThongTin_5.setStyleSheet("QTableWidget {\n"
"    border: 2px solid black;       /* Viền ngoài bảng */\n"
"    gridline-color: black;         /* Màu đường kẻ ô */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0;     /* Màu nền header */\n"
"    border: 1px solid #aaa;        /* Viền header */\n"
"}\n"
"")
        self.QtblXuatThongTin_5.setObjectName("QtblXuatThongTin_5")
        self.QtblXuatThongTin_5.setColumnCount(1)
        self.QtblXuatThongTin_5.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_5.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_5.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_5.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_5.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_5.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.QtblXuatThongTin_5.setHorizontalHeaderItem(0, item)
        self.QtblXuatThongTin_5.horizontalHeader().setDefaultSectionSize(200)
        self.tabWidget.addTab(self.widget, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tblDanhSach = QtWidgets.QTableWidget(parent=self.tab)
        self.tblDanhSach.setGeometry(QtCore.QRect(40, 130, 631, 341))
        self.tblDanhSach.setStyleSheet("QTableWidget {\n"
"    border: 2px solid black;       /* Viền ngoài bảng */\n"
"    gridline-color: black;         /* Màu đường kẻ ô */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0;     /* Màu nền header */\n"
"    border: 1px solid #aaa;        /* Viền header */\n"
"}\n"
"")
        self.tblDanhSach.setRowCount(10)
        self.tblDanhSach.setColumnCount(7)
        self.tblDanhSach.setObjectName("tblDanhSach")
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSach.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSach.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSach.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSach.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSach.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSach.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSach.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDanhSach.setHorizontalHeaderItem(6, item)
        self.tblDanhSach.horizontalHeader().setDefaultSectionSize(100)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 69, 441, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.radioButton = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.label_5 = QtWidgets.QLabel(parent=self.tab)
        self.label_5.setGeometry(QtCore.QRect(60, 0, 601, 61))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.btnNhapKho = QtWidgets.QPushButton(parent=self.tab_3)
        self.btnNhapKho.setGeometry(QtCore.QRect(230, 400, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnNhapKho.setFont(font)
        self.btnNhapKho.setStyleSheet("QPushButton {\n"
"    border: 1px solid black;         /* Viền đen 2px */\n"
"    border-radius: 10px;             /* Bo góc 10px */\n"
"    padding: 5px 15px;               /* Thêm padding cho nút */\n"
"    background-color: #f0f0f0;       /* Màu nền mặc định */\n"
"    color: black;                    /* Màu chữ */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0;       /* Màu nền khi di chuột vào */\n"
"    border: 2px solid darkgray;      /* Viền đổi thành màu xám đậm */\n"
"}\n"
"")
        self.btnNhapKho.setObjectName("btnNhapKho")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 651, 61))
        self.label_3.setObjectName("label_3")
        self.btnNhapKho_2 = QtWidgets.QPushButton(parent=self.tab_3)
        self.btnNhapKho_2.setGeometry(QtCore.QRect(130, 400, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnNhapKho_2.setFont(font)
        self.btnNhapKho_2.setStyleSheet("QPushButton {\n"
"    border: 1px solid black;         /* Viền đen 2px */\n"
"    border-radius: 10px;             /* Bo góc 10px */\n"
"    padding: 5px 15px;               /* Thêm padding cho nút */\n"
"    background-color: #f0f0f0;       /* Màu nền mặc định */\n"
"    color: black;                    /* Màu chữ */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0;       /* Màu nền khi di chuột vào */\n"
"    border: 2px solid darkgray;      /* Viền đổi thành màu xám đậm */\n"
"}\n"
"")
        self.btnNhapKho_2.setObjectName("btnNhapKho_2")
        self.QtblXuatThongTin_3 = QtWidgets.QTableWidget(parent=self.tab_3)
        self.QtblXuatThongTin_3.setGeometry(QtCore.QRect(30, 80, 321, 311))
        self.QtblXuatThongTin_3.setStyleSheet("QTableWidget {\n"
"    border: 2px solid black;       /* Viền ngoài bảng */\n"
"    gridline-color: black;         /* Màu đường kẻ ô */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0;     /* Màu nền header */\n"
"    border: 1px solid #aaa;        /* Viền header */\n"
"}\n"
"")
        self.QtblXuatThongTin_3.setObjectName("QtblXuatThongTin_3")
        self.QtblXuatThongTin_3.setColumnCount(1)
        self.QtblXuatThongTin_3.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.QtblXuatThongTin_3.setHorizontalHeaderItem(0, item)
        self.QtblXuatThongTin_3.horizontalHeader().setDefaultSectionSize(200)
        self.QtblXuatThongTin_4 = QtWidgets.QTableWidget(parent=self.tab_3)
        self.QtblXuatThongTin_4.setGeometry(QtCore.QRect(370, 80, 321, 311))
        self.QtblXuatThongTin_4.setStyleSheet("QTableWidget {\n"
"    border: 2px solid black;       /* Viền ngoài bảng */\n"
"    gridline-color: black;         /* Màu đường kẻ ô */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0;     /* Màu nền header */\n"
"    border: 1px solid #aaa;        /* Viền header */\n"
"}\n"
"")
        self.QtblXuatThongTin_4.setObjectName("QtblXuatThongTin_4")
        self.QtblXuatThongTin_4.setColumnCount(1)
        self.QtblXuatThongTin_4.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_4.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_4.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.QtblXuatThongTin_4.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.QtblXuatThongTin_4.setHorizontalHeaderItem(0, item)
        self.QtblXuatThongTin_4.horizontalHeader().setDefaultSectionSize(200)
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Thông báo chung"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Thông báo chi tiết</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Xóa thông báo"))
        self.pushButton_4.setText(_translate("MainWindow", "Xóa tất cả thông báo"))
        item = self.QtblXuatThongTin_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã sản phẩm"))
        item = self.QtblXuatThongTin_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên sản phẩm"))
        item = self.QtblXuatThongTin_5.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Danh mục"))
        item = self.QtblXuatThongTin_5.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Đơn giá"))
        item = self.QtblXuatThongTin_5.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Số lượng"))
        item = self.QtblXuatThongTin_5.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Trạng thái"))
        item = self.QtblXuatThongTin_5.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ngày nhập kho"))
        item = self.QtblXuatThongTin_5.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ngày hết hạn"))
        item = self.QtblXuatThongTin_5.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Hàng tồn tối thiểu"))
        item = self.QtblXuatThongTin_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Thông tin hàng hóa trong kho"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Trang chủ"))
        item = self.tblDanhSach.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tblDanhSach.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã sản phẩm"))
        item = self.tblDanhSach.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên sản phẩm"))
        item = self.tblDanhSach.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Đơn giá"))
        item = self.tblDanhSach.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Số lượng"))
        item = self.tblDanhSach.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ngày nhập kho"))
        item = self.tblDanhSach.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Hạn sử dụng"))
        item = self.tblDanhSach.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Trạng thái"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Danh mục:</span></p></body></html>"))
        self.radioButton.setText(_translate("MainWindow", "Thực phẩm"))
        self.radioButton_2.setText(_translate("MainWindow", "Đồ gia dụng"))
        self.radioButton_3.setText(_translate("MainWindow", "Văn phòng phẩm"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#000000;\">DANH SÁCH HÀNG TRONG KHO</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Danh sách"))
        self.btnNhapKho.setText(_translate("MainWindow", "Nhập kho"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#000000;\">NHẬP KHO</span></p></body></html>"))
        self.btnNhapKho_2.setText(_translate("MainWindow", "Xóa"))
        item = self.QtblXuatThongTin_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã sản phẩm"))
        item = self.QtblXuatThongTin_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên sản phẩm"))
        item = self.QtblXuatThongTin_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Danh mục"))
        item = self.QtblXuatThongTin_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Đơn giá"))
        item = self.QtblXuatThongTin_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Số lượng"))
        item = self.QtblXuatThongTin_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ngày nhập kho"))
        item = self.QtblXuatThongTin_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ngày hết hạn"))
        item = self.QtblXuatThongTin_3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Hàng tồn tối thiểu"))
        item = self.QtblXuatThongTin_3.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Trạng thái"))
        item = self.QtblXuatThongTin_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nhập thông tin"))
        item = self.QtblXuatThongTin_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã sản phẩm"))
        item = self.QtblXuatThongTin_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên sản phẩm"))
        item = self.QtblXuatThongTin_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Danh mục"))
        item = self.QtblXuatThongTin_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Đơn giá"))
        item = self.QtblXuatThongTin_4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Số lượng"))
        item = self.QtblXuatThongTin_4.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Trạng thái"))
        item = self.QtblXuatThongTin_4.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ngày nhập kho"))
        item = self.QtblXuatThongTin_4.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ngày hết hạn"))
        item = self.QtblXuatThongTin_4.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Hàng tồn tối thiểu"))
        item = self.QtblXuatThongTin_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Thông tin hàng hóa trong kho"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Xuất - Nhập kho"))
